[rf]
device_name = uhd
device_args = type=x300,addr=192.168.114.2
tx_gain = 5
rx_gain = 40
freq_offset = 0
srate = 11.52e6
nof_antennas = 1

[rat.eutra]
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 52
nof_prb = 52
dl_nr_arfcn = 368500
ssb_nr_arfcn = 368410

[usim]
mode = soft
algo = milenage
opc  = E8ED289DEBA952E4283B54E88E6183CA
k    = 465B5CE8B199B49FAA5F0A2EE238A6BC
imsi = 001010123456780
imei = 353490069873319

[rrc]
release = 15

[nas]
apn = internet
apn_protocol = ipv4

[gw]
ip_devname = tun_srsue
ip_netmask = 255.255.255.0

[gui]
enable = false

[log]
all_level = info
all_hex_limit = 32
filename = /tmp/srsue_usrp_fdd.log
file_max_size = -1

[general]
metrics_period_secs = 1.0
